export const LOAD_PROFILES = 'LOAD_PROFILES';
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const SAVE_PROFILE = 'SAVE_PROFILE';
export const STORE_PROFILE = 'STORE_PROFILE';

export const LOAD_REPORTS = 'LOAD_REPORTS';
export const LOAD_REPORT = 'LOAD_REPORT';

export const LOAD_PROCESSORS = 'LOAD_PROCESSORS';
export const STORE_PROCESSOR = 'STORE_PROCESSOR';

export const STORE_DATA_RESOURCE = 'STORE_DATA_RESOURCE';
export const SAVE_DATA_RESOURCE = 'SAVE_DATA_RESOURCE';
export const LOAD_DATA_RESOURCES = 'LOAD_DATA_RESOURCES';
export const STORE_DATA_RESOURCES = 'STORE_DATA_RESOURCES';
