export const LOAD_PROFILES = 'LOAD_PROFILES';
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const SAVE_PROFILE = 'SAVE_PROFILE';
export const STORE_PROFILE = 'STORE_PROFILE';

export const LOAD_REPORTS = 'LOAD_REPORTS';
export const LOAD_REPORT = 'LOAD_REPORT';

export const LOAD_PROCESSORS = 'LOAD_PROCESSORS';
export const STORE_PROCESSOR = 'STORE_PROCESSOR';
