export const SET_PROFILES = 'SET_PROFILES';
export const RESET_PROFILES = 'RESET_PROFILES';
export const SET_CURRENT_PROFILE = 'SET_CURRENT_PROFILE';
export const UNSET_CURRENT_PROFILE = 'UNSET_CURRENT_PROFILE';

export const SET_REPORTS = 'SET_REPORTS';
export const RESET_REPORTS = 'RESET_REPORTS';
export const SET_CURRENT_REPORT = 'SET_CURRENT_REPORT';
export const UNSET_CURRENT_REPORT = 'UNSET_CURRENT_REPORT';

export const SET_PROCESSORS = 'SET_PROCESSORS';
export const RESET_PROCESSORS = 'RESET_PROCESSORS';
export const SET_CURRENT_PROCESSOR = 'SET_CURRENT_PROCESSOR';
export const UNSET_CURRENT_PROCESSOR = 'UNSET_CURRENT_PROCESSOR';

export const SET_USERS = 'SET_USERS';
export const RESET_USERS = 'RESET_USERS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';

export const APPEND_DATA_RESOURCES = 'SET_DATA_RESOURCES';
export const SET_DATA_RESOURCE_PROVIDER_IN_PROGRESS = 'SET_DATA_RESOURCE_PROVIDER_IN_PROGRESS';
export const SET_DATA_RESOURCE_PROVIDER_PAGE_COUNT = 'SET_DATA_RESOURCE_PROVIDER_PAGE_COUNT';
export const RESET_DATA_RESOURCES = 'RESET_DATA_RESOURCES';
export const SET_CURRENT_DATA_RESOURCE = 'SET_CURRENT_DATA_RESOURCE';
export const UNSET_CURRENT_DATA_RESOURCE = 'UNSET_CURRENT_DATA_RESOURCE';
export const SET_DATA_RESOURCES_PAGE = 'SET_DATA_RESOURCES_PAGE';
export const SET_DATA_RESOURCES_SORT = 'SET_DATA_RESOURCES_SORT';
export const SET_DATA_RESOURCES_ORDER = 'SET_DATA_RESOURCES_ORDER';
export const SET_DATA_RESOURCES_FILTERS = 'SET_DATA_RESOURCES_FILTERS';

export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';
export const UNSET_LOGGED_IN_USER = 'UNSET_LOGGED_IN_USER';
