export const SET_PROFILES = 'SET_PROFILES';
export const RESET_PROFILES = 'RESET_PROFILES';
export const SET_CURRENT_PROFILE = 'SET_CURRENT_PROFILE';
export const UNSET_CURRENT_PROFILE = 'UNSET_CURRENT_PROFILE';

export const SET_REPORTS = 'SET_REPORTS';
export const RESET_REPORTS = 'RESET_REPORTS';
export const SET_CURRENT_REPORT = 'SET_CURRENT_REPORT';
export const UNSET_CURRENT_REPORT = 'UNSET_CURRENT_REPORT';

export const SET_PROCESSORS = 'SET_PROCESSORS';
export const RESET_PROCESSORS = 'RESET_PROCESSORS';
